name: Daily Surf Notifier

on:
  schedule:
    # Runs at 16:38 BST (UK daylight savings time), which is 15:38 UTC
    - cron: "46 08 * * *"
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run surf notifier script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          STORMGLASS_API_KEY: ${{ secrets.STORMGLASS_API_KEY }}
        run: python surf-notifier
